name: inotes
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Flutter SDK dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# Flutter packages
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1
  flutter_bloc: ^8.1.6
  flutter_quill: ^10.8.5
  flutter_secure_storage: ^9.2.2

# Dart packages
  bloc: ^8.1.4
  build_runner: ^2.4.11
  path_provider: ^2.1.4
  uuid: ^4.5.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  appflowy_editor: ^4.0.0
  dio: ^5.7.0
  image_picker: ^1.1.2
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/placeholder_avatar.png